### ISSUE TITLE
Windows CLI

### ISSUE THREAD

**Issue by lukesnider** [wpengine/headless-docs#16]
Is there currently a CLI for windows? Or is this in the works?

**Comment by matt-landers** [comment]
We are working on distributing all of the versions, but for now, here is a windows version for v0.0.4. https://drive.google.com/file/d/1XLJoXXa2OrbPDVHAexa0mIIlYuURi8zA/view

**Comment by matt-landers** [comment]
This is now available via `npm i -g @wpengine/headless-cli`
