### ISSUE TITLE
gitignore should include .env.local.sample

### ISSUE THREAD

**Issue by bowiedev** [wpengine/headless-docs#42]
The system seems to ingest .env.local.sample. 
This configured my WORDPRESS_URL in the WPE Portal to http://yoururl. 
Seems to be specifically allowed in the gitignore of the project. 
I received a 500 error when building but once deleted, committed and pushed, the build worked.

**Comment by DonNateR** [comment]
Thanks @bowiedev, I'll have a PR for this soon.
