### ISSUE TITLE
We no longer require users to install plugins manually nor create a new WP install if they don't have one.

### ISSUE THREAD

**Issue by ikedracka** [wpengine/headless-docs#94]
Ever since last sprint, users don't have to install "FaustWP", "WPGraphQL" and "Atlas Content Modeler" manually as a part of their prerequisites - during Atlas app creation flow when they link their Atlas environment to their WP install, we'll "scan" this install for installed plugins and add remaining plugins in case any of the three mentioned above is missing. 

Not sure how to address this change in docs - but user should be informed that they no longer have to manually install all the plugins we require for the "Atlas starter". They can also create a brand new install in this flow which also will be provisioned with all the relevant plugins. See screenshot below:
![image](https://user-images.githubusercontent.com/15729608/146437717-88533df3-fe9a-4682-9448-7eb4db71595a.png)

PS This flow will be soon adjusted to cater for users that do not want to get all plugins installed on their WordPress install (because, for example, they use different framework than Faust). We'll give user an option to select the plugins they want to install, but for now the default (all three plugins are gonna be installed on user's selected WP) cannot be changed.

That being said, none of these adjustments are in place in Portal now, so once they're there I'll create a new issue to reflect them in docs

**Comment by kellenmace** [comment]
Fixed this a while ago 👍
